version: "3"
services:
  jekyll:
      image: jekyll/jekyll:3.8
      command: jekyll serve --force_polling --incremental
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll
          #- ./Gemfile:/srv/jekyll/Gemfile
          #- ./Gemfile.lock:/srv/jekyll/Gemfile.lock
      environment:
        JEKYLL_UID: 1001
        JEKYLL_GID: 1001
